import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import FloatingNav from "@/components/FloatingNav";
import { AmbientBg } from "@/lib/glass";

const sectionStyle: React.CSSProperties = {
  marginBottom: "48px",
};

const headingStyle: React.CSSProperties = {
  fontSize: "18px",
  fontWeight: 600,
  color: "rgba(255,255,255,0.88)",
  fontFamily: "'Geist', sans-serif",
  marginBottom: "12px",
};

const bodyStyle: React.CSSProperties = {
  fontSize: "14px",
  color: "rgba(255,255,255,0.55)",
  fontFamily: "'Geist', sans-serif",
  lineHeight: 1.75,
};

export default function Terms() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#06060b",
        fontFamily: "'Geist', sans-serif",
        position: "relative",
      }}
    >      <AmbientBg />

      <FloatingNav />

      <div style={{ position: "relative", zIndex: 1, paddingTop: "112px", paddingBottom: "96px", paddingLeft: "24px", paddingRight: "24px" }}>
        <div style={{ maxWidth: "760px", margin: "0 auto" }}>

          <Link
            to="/"
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "6px",
              fontSize: "13px",
              color: "rgba(255,255,255,0.4)",
              textDecoration: "none",
              fontFamily: "'Geist', sans-serif",
              marginBottom: "40px",
            }}
          >
            <ArrowLeft style={{ width: "14px", height: "14px" }} />
            Back to home
          </Link>

          <h1
            style={{
              fontSize: "clamp(32px, 5vw, 48px)",
              fontWeight: 700,
              color: "rgba(255,255,255,0.88)",
              fontFamily: "'Geist', sans-serif",
              marginBottom: "8px",
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
            }}
          >
            Terms of Service
          </h1>
          <p style={{ fontSize: "14px", color: "rgba(255,255,255,0.35)", fontFamily: "'Geist', sans-serif", marginBottom: "56px" }}>
            Last updated: March 2026
          </p>

          <div style={sectionStyle}>
            <h2 style={headingStyle}>1. Acceptance of Terms</h2>
            <p style={bodyStyle}>
              By accessing or using Buildable Labs, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, you may not use the service. We may update these terms at any time — continued use of the service constitutes acceptance of any changes.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={headingStyle}>2. Use of the Service</h2>
            <p style={bodyStyle}>
              Buildable Labs provides an AI-powered platform for creating and deploying Discord bots. You agree to use the service only for lawful purposes and in accordance with Discord's Terms of Service. You are responsible for all bots you create, their behaviour, and how they interact with Discord servers and users.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={headingStyle}>3. Account Responsibility</h2>
            <p style={bodyStyle}>
              You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorised use of your account. Buildable Labs is not liable for any loss resulting from unauthorised account access.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={headingStyle}>4. Credits and Billing</h2>
            <p style={bodyStyle}>
              Buildable Labs operates on a credit-based system. Free accounts receive a daily allotment of credits. Pro plans are billed monthly or annually. Credits are non-refundable and expire at the end of each billing period. We reserve the right to change pricing with 30 days notice.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={headingStyle}>5. Intellectual Property</h2>
            <p style={bodyStyle}>
              The code generated by Buildable AI for your bots is yours to use. Buildable Labs retains ownership of the platform, UI, underlying AI systems, and all Buildable brand assets. You may not copy, modify, or distribute the Buildable platform itself without written permission.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={headingStyle}>6. Termination</h2>
            <p style={bodyStyle}>
              We reserve the right to suspend or terminate your account at any time if you violate these terms, abuse the platform, or engage in activity that harms other users. You may delete your account at any time through the dashboard settings. Upon termination, your bots will be taken offline.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={headingStyle}>7. Limitation of Liability</h2>
            <p style={bodyStyle}>
              Buildable Labs is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to bot downtime, data loss, or interactions between bots and Discord users.
            </p>
          </div>

          <div style={sectionStyle}>
            <h2 style={headingStyle}>8. Contact</h2>
            <p style={bodyStyle}>
              For questions about these Terms, please contact us via{" "}
              <a href="/contact" style={{ color: "rgba(140,100,255,0.8)", textDecoration: "none" }}>
                our contact page
              </a>
              .
            </p>
          </div>

          <div
            style={{
              marginTop: "64px",
              paddingTop: "32px",
              borderTop: "1px solid rgba(255,255,255,0.08)",
              display: "flex",
              flexWrap: "wrap",
              gap: "20px",
            }}
          >
            <Link
              to="/privacy"
              style={{
                fontSize: "13px",
                color: "rgba(140,100,255,0.8)",
                textDecoration: "none",
                fontFamily: "'Geist', sans-serif",
              }}
            >
              Privacy Policy
            </Link>
            <span style={{ color: "rgba(255,255,255,0.12)", fontSize: "13px" }}>|</span>
            <Link
              to="/"
              style={{
                fontSize: "13px",
                color: "rgba(140,100,255,0.8)",
                textDecoration: "none",
                fontFamily: "'Geist', sans-serif",
              }}
            >
              Back to Home
            </Link>
          </div>

        </div>
      </div>
    </div>
  );
}
